services:
  ipa-renamer-watch:
    build: .
    image: ipa-renamer-watch:latest
    container_name: ipa-renamer-watch
    environment:
      - WATCH_DIR=/app/watched
      - OUTPUT_DIR=/app/output
    volumes:
      - ./watched:/app/watched
      - ./output:/app/output
    restart: unless-stopped
