# GitHub Actions workflow to build and push Docker image to GHCR
name: Build and Push Docker image to GHCR

on:
  push:
    branches: [ rewrite, master ]
  workflow_dispatch:

jobs:
  build-and-push:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (${{ matrix.arch }})
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/${{ matrix.arch }}
          provenance: true
          sbom: true
          tags: ghcr.io/kagurazakairis/golang-ipa-renamer-watch:${{ matrix.arch }},ghcr.io/kagurazakairis/golang-ipa-renamer-watch:latest
